"""empty message

Revision ID: 4cadc647b7c5
Revises: 
Create Date: 2017-02-25 19:14:46.930784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cadc647b7c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_app', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ml_app', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ml_app', type_='foreignkey')
    op.drop_column('ml_app', 'owner_id')
    # ### end Alembic commands ###
