"""empty message

Revision ID: 4d04d47b8ca2
Revises: 
Create Date: 2017-02-25 13:14:18.378136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d04d47b8ca2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'audio_sample_ml_class_id_fkey', 'audio_sample', type_='foreignkey')
    op.create_foreign_key(None, 'audio_sample', 'ml_class', ['ml_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audio_sample', type_='foreignkey')
    op.create_foreign_key(u'audio_sample_ml_class_id_fkey', 'audio_sample', 'ml_class', ['ml_class_id'], ['id'], ondelete=u'CASCADE')
    # ### end Alembic commands ###
