"""empty message

Revision ID: f6e8cc63a021
Revises: 5b3566eb2c9f
Create Date: 2017-02-25 21:06:47.111660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e8cc63a021'
down_revision = '5b3566eb2c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'audio_sample_ml_class_id_fkey', 'audio_sample', type_='foreignkey')
    op.create_foreign_key(None, 'audio_sample', 'ml_class', ['ml_class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audio_sample', type_='foreignkey')
    op.create_foreign_key(u'audio_sample_ml_class_id_fkey', 'audio_sample', 'ml_class', ['ml_class_id'], ['id'])
    # ### end Alembic commands ###
